<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <title>Barbearia Pedroso</title>
</head>

<body>

  <!-- Seção de Navegação -->
  <header>
    <h1>Barbearia Pedroso</h1>
    <nav>
      <ul>
        <li><a href="#equipe">Equipe</a></li>
        <li><a href="#servicos">Serviços</a></li>
        <li><a href="#contato">Contato</a></li>
      </ul>
    </nav>
  </header>
  <!-- Seção de Serviços -->
  <section id="servicos">
    <h2>Nossos Serviços</h2>
    <div class="service">
      <h3>Corte de Cabelo</h3>
      <p>Oferecemos cortes modernos para homens e mulheres.</p>
    </div>
    <div class="service">
      <h3>Barba</h3>
      <p>Serviços especializados para manter a sua barba impecável.</p>
    </div>
    <div class="service">
      <h3>Pacote Completo</h3>
      <p>Experimente nosso pacote completo, incluindo corte de cabelo e barba.</p>
    </div>
  </section>

body {
  font-family: 'Arial', sans-serif;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

header {
  background-color: #333;
  color: #fff;
  text-align: center;
  padding: 1em;
}

nav ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
}

nav li {
  display: inline;
  margin-right: 20px;
}
